export const FETCH_LIST_SLIDER = 'FETCH_LIST_SLIDER';
export const FETCH_LIST_RECENTLY_LISTEN = 'FETCH_LIST_RECENTLY_LISTEN';
export const NEXT_OR_PREV_SONG = 'NEXT_OR_PREV_SONG';
export const REMOVE_PLAYLIST = 'REMOVE_PLAYLIST';
export const ADD_SONG_TO_QUEUE = 'ADD_SONG_TO_QUEUE';
export const ADD_ALBUM_TO_QUEUE = 'ADD_ALBUM_TO_QUEUE';